server:
  port: 8082

spring:
	application:
		name: MsCustomer
spring:
  cloud: 
    config:      
      enabled: true
      discovery:
        enabled: true
        serviceId: configServer
  jpa:
    hibernate:
      ddl-auto: create-drop
      
management:
  security:
    enabled: false
  address: 127.0.0.1

  
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true 
