server:
  port: ${PORT:8082}

spring:
	application:
		name: MsCustomer
spring:
  cloud: 
    config:      
      enabled: true
    discovery:
      enabled: true
      serviceId: configServer
  jpa:
    hibernate:
      ddl-auto: create-drop
      
management:
  security:
    enabled: false

  
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true 
